dojo.provide("dojo.widget.TreeEmphasizeOnSelect");
dojo.require("dojo.widget.HtmlWidget");
dojo.require("dojo.widget.TreeSelectorV3");
dojo.require("dojo.html.selection");
dojo.widget.defineWidget("dojo.widget.TreeEmphasizeOnSelect",dojo.widget.HtmlWidget,{selector:"",initialize:function(){
this.selector=dojo.widget.byId(this.selector);
dojo.event.topic.subscribe(this.selector.eventNames.select,this,"onSelect");
dojo.event.topic.subscribe(this.selector.eventNames.deselect,this,"onDeselect");
},onSelect:function(_1){
_1.node.viewEmphasize();
},onDeselect:function(_2){
_2.node.viewUnemphasize();
}});
