/*
	Copyright (c) 2004-2006, The Dojo Foundation
	All Rights Reserved.

	Licensed under the Academic Free License version 2.1 or above OR the
	modified BSD license. For more information on Dojo licensing, see:

		http://dojotoolkit.org/community/licensing.shtml
*/

dojo.provide("nls.dojo_ja-jp");dojo.provide("dojo.i18n.calendar.nls.gregorian");dojo.i18n.calendar.nls.gregorian._built=true;dojo.provide("dojo.i18n.calendar.nls.gregorian.ja_jp");dojo.i18n.calendar.nls.gregorian.ja_jp={"days-standAlone-narrow":["日","月","火","水","木","金","土"],"timeFormat-full":"H'時'mm'分'ss'秒'z","eras":["紀元前","西暦"],"timeFormat-medium":"H:mm:ss","dateFormat-medium":"yyyy/MM/dd","am":"午前","months-format-abbr":["1 月","2 月","3 月","4 月","5 月","6 月","7 月","8 月","9 月","10 月","11 月","12 月"],"dateFormat-full":"yyyy'年'M'月'd'日'EEEE","days-format-abbr":["日","月","火","水","木","金","土"],"timeFormat-long":"H:mm:ss:z","timeFormat-short":"H:mm","pm":"午後","months-format-wide":["1 月","2 月","3 月","4 月","5 月","6 月","7 月","8 月","9 月","10 月","11 月","12 月"],"dateFormat-long":"yyyy'年'M'月'd'日'","days-format-wide":["日曜日","月曜日","火曜日","水曜日","木曜日","金曜日","土曜日"],"field-weekday":"Day of the Week","field-second":"Second","field-week":"Week","months-standAlone-narrow":["1","2","3","4","5","6","7","8","9","10","11","12"],"field-year":"Year","field-minute":"Minute","field-hour":"Hour","field-day":"Day","field-dayperiod":"Dayperiod","field-month":"Month","dateFormat-short":"yy/MM/dd","field-era":"Era","field-zone":"Zone"};dojo.provide("dojo.i18n.calendar.nls.gregorianExtras");dojo.i18n.calendar.nls.gregorianExtras._built=true;dojo.provide("dojo.i18n.calendar.nls.gregorianExtras.ja_jp");dojo.i18n.calendar.nls.gregorianExtras.ja_jp={"dateFormat-yearOnly":"yyyy年"};dojo.provide("dojo.widget.nls.TimePicker");dojo.widget.nls.TimePicker._built=true;dojo.provide("dojo.widget.nls.TimePicker.ja_jp");dojo.widget.nls.TimePicker.ja_jp={"any":"any"};dojo.provide("dojo.widget.nls.DropdownDatePicker");dojo.widget.nls.DropdownDatePicker._built=true;dojo.provide("dojo.widget.nls.DropdownDatePicker.ja_jp");dojo.widget.nls.DropdownDatePicker.ja_jp={"selectDate":"Select a date"};dojo.provide("dojo.widget.nls.DropdownTimePicker");dojo.widget.nls.DropdownTimePicker._built=true;dojo.provide("dojo.widget.nls.DropdownTimePicker.ja_jp");dojo.widget.nls.DropdownTimePicker.ja_jp={"selectTime":"Select time"};