
dojo.provide("dojo.widget.Checkbox");dojo.require("dojo.widget.*");dojo.require("dojo.widget.HtmlWidget");dojo.require("dojo.event.*");dojo.require("dojo.html.style");dojo.require("dojo.html.selection");dojo.widget.defineWidget(
"dojo.widget.Checkbox",dojo.widget.HtmlWidget,{templatePath: dojo.uri.moduleUri("dojo.widget", "templates/Checkbox.html"),_type: "checkbox",name: "",id: "",checked: false,tabIndex: "",value: "on",_groups: { },postMixInProperties: function(){dojo.widget.Checkbox.superclass.postMixInProperties.apply(this, arguments);if(!this.disabled && this.tabIndex==""){ this.tabIndex="0"; }},fillInTemplate: function(){this._setValue(this.checked);},postCreate: function(){var notcon = true;this.id = this.id !="" ? this.id : this.widgetId;if(this.id != ""){var labels = document.getElementsByTagName("label");if (labels != null && labels.length > 0){for(var i=0; i<labels.length; i++){if (labels[i].htmlFor == this.id){labels[i].id = (labels[i].htmlFor + "label");this._connectEvents(labels[i]);dojo.widget.wai.setAttr(this.domNode, "waiState", "labelledby", labels[i].id);break;}}
}}
this._connectEvents(this.domNode);this.inputNode.checked=this.checked;this._register();},onImageLoad: function(){this.imageLoaded = true;this.width = this.imageNode.width/6;this.height = this.imageNode.height/2;this.spacerNode.style.width =  this.width + "px";this.spacerNode.style.height =  this.height + "px";this.spacerNode.style.display = "";this.imageNode.style.display="";this.inputNode.style.display="none";this._setValue(this.checked);},uninitialize: function(){this._deregister();},_connectEvents: function( node){dojo.event.connect(node, "onmouseover", this, "mouseOver");dojo.event.connect(node, "onmouseout", this, "mouseOut");dojo.event.connect(node, "onkey", this, "onKey");dojo.event.connect(node, "onclick", this, "_onClick");dojo.html.disableSelection(node);},_onClick: function( e){if(this.disabled == false){this.setValue(!this.checked);}
e.stopPropagation();this.onClick();},_register: function(){if(this._groups[this.name] == null){this._groups[this.name]=[];}
this._groups[this.name].push(this);},_deregister: function(){var idx = dojo.lang.find(this._groups[this.name], this, true);this._groups[this.name].splice(idx, 1);},setValue: function( bool){this._setValue(bool);},onClick: function(){},onKey: function( e){var k = dojo.event.browser.keys;if(e.key == " "){this._onClick(e);}},mouseOver: function( e){this.hover=true;this._setValue(this.checked);},mouseOut: function( e){this.hover=false;this._setValue(this.checked);},_topOffset: 0,_setValue: function( bool){this.checked = bool;this.inputNode.checked = this.checked;if(this.disabled){this.inputNode.setAttribute("disabled",true);}else{this.inputNode.removeAttribute("disabled");}
dojo.widget.wai.setAttr(this.domNode, "waiState", "checked", this.checked);if(this.imageLoaded){var left = (this.checked ? 0 : this.width ) + (this.disabled ? this.width*2 : (this.hover ? this.width*4 : 0 ));var s = this.imageNode.style;s.marginLeft = -1*left + "px";s.marginTop = -1*this._topOffset + "px";var clip = "rect(" + this._topOffset + "px, " + (left+this.width) + "px, " +
(this._topOffset+this.height) + "px, " + left + "px)";s.clip =  clip;}}
}
);dojo.widget.defineWidget(
"dojo.widget.RadioButton",dojo.widget.Checkbox,{_type: "radio",_onClick: function( e){if(!this.disabled && !this.checked){this.setValue(true);}
e.stopPropagation();this.onClick();},setValue: function( bool){this._setValue(bool);if(bool){dojo.lang.forEach(this._groups[this.name], function(widget){if(widget != this){widget._setValue(false);}}, this);}},onImageLoad: function(){this._topOffset = this.imageNode.height/2;dojo.widget.Checkbox.prototype.onImageLoad.call(this);}}
);