
dojo.provide("dojo.widget.ComboBox");dojo.require("dojo.widget.*");dojo.require("dojo.event.*");dojo.require("dojo.io.*");dojo.require("dojo.lfx.*");dojo.require("dojo.html.*");dojo.require("dojo.html.display");dojo.require("dojo.html.layout");dojo.require("dojo.html.iframe");dojo.require("dojo.string");dojo.require("dojo.widget.html.stabile");dojo.require("dojo.widget.PopupContainer");dojo.widget.incrementalComboBoxDataProvider = function( url,  limit,  timeout){this.searchUrl = url;this.inFlight = false;this.activeRequest = null;this.allowCache = false;this.cache = {};this.init = function( cbox){this.searchUrl = cbox.dataUrl;};this.addToCache = function( keyword,  data){if(this.allowCache){this.cache[keyword] = data;}};this.startSearch = function( searchStr,  type,  ignoreLimit){if(this.inFlight){}
var tss = encodeURIComponent(searchStr);var realUrl = dojo.string.substituteParams(this.searchUrl, {"searchString": tss});var _this = this;var request = dojo.io.bind({url: realUrl,method: "get",mimetype: "text/json",load: function(type, data, evt){_this.inFlight = false;if(!dojo.lang.isArray(data)){var arrData = [];for(var key in data){arrData.push([data[key], key]);}
data = arrData;}
_this.addToCache(searchStr, data);_this.provideSearchResults(data);}});this.inFlight = true;};};dojo.widget.ComboBoxDataProvider = function( dataPairs,  limit,  timeout){this.data = [];this.searchTimeout = timeout || 500;this.searchLimit = limit || 30;this.searchType = "STARTSTRING";this.caseSensitive = false;this._lastSearch = "";this._lastSearchResults = null;this.init = function( cbox,  node){if(!dojo.string.isBlank(cbox.dataUrl)){this.getData(cbox.dataUrl);}else{if((node)&&(node.nodeName.toLowerCase() == "select")){var opts = node.getElementsByTagName("option");var ol = opts.length;var data = [];for(var x=0; x<ol; x++){var text = opts[x].textContent || opts[x].innerText || opts[x].innerHTML;var keyValArr = [String(text), String(opts[x].value)];data.push(keyValArr);if(opts[x].selected){cbox.setAllValues(keyValArr[0], keyValArr[1]);}}
this.setData(data);}}};this.getData = function( url){dojo.io.bind({url: url,load: dojo.lang.hitch(this, function(type, data, evt){if(!dojo.lang.isArray(data)){var arrData = [];for(var key in data){arrData.push([data[key], key]);}
data = arrData;}
this.setData(data);}),mimetype: "text/json"});};this.startSearch = function( searchStr,  type,  ignoreLimit){this._preformSearch(searchStr, type, ignoreLimit);};this._preformSearch = function( searchStr,  type,  ignoreLimit){var st = type||this.searchType;var ret = [];if(!this.caseSensitive){searchStr = searchStr.toLowerCase();}
for(var x=0; x<this.data.length; x++){if((!ignoreLimit)&&(ret.length >= this.searchLimit)){break;}
var dataLabel = new String((!this.caseSensitive) ? this.data[x][0].toLowerCase() : this.data[x][0]);if(dataLabel.length < searchStr.length){continue;}
if(st == "STARTSTRING"){if(searchStr == dataLabel.substr(0, searchStr.length)){ret.push(this.data[x]);}}else if(st == "SUBSTRING"){if(dataLabel.indexOf(searchStr) >= 0){ret.push(this.data[x]);}}else if(st == "STARTWORD"){var idx = dataLabel.indexOf(searchStr);if(idx == 0){ret.push(this.data[x]);}
if(idx <= 0){continue;}
var matches = false;while(idx!=-1){if(" ,/(".indexOf(dataLabel.charAt(idx-1)) != -1){matches = true; break;}
idx = dataLabel.indexOf(searchStr, idx+1);}
if(!matches){continue;}else{ret.push(this.data[x]);}}}
this.provideSearchResults(ret);};this.provideSearchResults = function( resultsDataPairs){};this.addData = function( pairs){this.data = this.data.concat(pairs);};this.setData = function( pdata){this.data = pdata;};if(dataPairs){this.setData(dataPairs);}};dojo.widget.defineWidget(
"dojo.widget.ComboBox",dojo.widget.HtmlWidget,{isContainer: false,forceValidOption: false,searchType: "stringstart",dataProvider: null,startSearch: function( searchString){},selectNextResult: function(){},selectPrevResult: function(){},setSelectedResult: function(){},autoComplete: true,name: "",textInputNode: null,comboBoxValue: null,comboBoxSelectionValue: null,optionsListWrapper: null,optionsListNode: null,downArrowNode: null,searchTimer: null,searchDelay: 100,dataUrl: "",fadeTime: 200,maxListLength: 8,mode: "local",selectedResult: null,_highlighted_option: null,_prev_key_backspace: false,_prev_key_esc: false,_gotFocus: false,_mouseover_list: false,dataProviderClass: "dojo.widget.ComboBoxDataProvider",buttonSrc: dojo.uri.dojoUri("src/widget/templates/images/combo_box_arrow.png"),dropdownToggle: "fade",templatePath: dojo.uri.dojoUri("src/widget/templates/ComboBox.html"),templateCssPath: dojo.uri.dojoUri("src/widget/templates/ComboBox.css"),setValue: function( value){this.comboBoxValue.value = value;if (this.textInputNode.value != value){this.textInputNode.value = value;dojo.widget.html.stabile.setState(this.widgetId, this.getState(), true);this.onValueChanged(value);}},onValueChanged: function(){ },getValue: function(){return this.comboBoxValue.value;},getState: function(){return {value: this.getValue()};},setState: function( state){this.setValue(state.value);},enable:function(){this.disabled=false;this.textInputNode.removeAttribute("disabled");},disable: function(){this.disabled = true;this.textInputNode.setAttribute("disabled",true);},getCaretPos: function( element){if(dojo.lang.isNumber(element.selectionStart)){return element.selectionStart;}else if(dojo.render.html.ie){var tr = document.selection.createRange().duplicate();var ntr = element.createTextRange();tr.move("character",0);ntr.move("character",0);try {ntr.setEndPoint("EndToEnd", tr);return String(ntr.text).replace(/\r/g,"").length;} catch (e){return 0;}}},setCaretPos: function( element,  location){location = parseInt(location);this.setSelectedRange(element, location, location);},setSelectedRange: function( element,  start,  end){if(!end){ end = element.value.length; }
if(element.setSelectionRange){element.focus();element.setSelectionRange(start, end);}else if(element.createTextRange){var range = element.createTextRange();with(range){collapse(true);moveEnd('character', end);moveStart('character', start);select();}}else{element.value = element.value;element.blur();element.focus();var dist = parseInt(element.value.length)-end;var tchar = String.fromCharCode(37);var tcc = tchar.charCodeAt(0);for(var x = 0; x < dist; x++){var te = document.createEvent("KeyEvents");te.initKeyEvent("keypress", true, true, null, false, false, false, false, tcc, tcc);element.dispatchEvent(te);}}},_handleKeyEvents: function( evt){if(evt.ctrlKey || evt.altKey || !evt.key){ return; }
this._prev_key_backspace = false;this._prev_key_esc = false;var k = dojo.event.browser.keys;var doSearch = true;switch(evt.key){case k.KEY_DOWN_ARROW:
if(!this.popupWidget.isShowingNow){this.startSearchFromInput();}
this.highlightNextOption();dojo.event.browser.stopEvent(evt);return;case k.KEY_UP_ARROW:
this.highlightPrevOption();dojo.event.browser.stopEvent(evt);return;case k.KEY_TAB:
if(!this.autoComplete && this.popupWidget.isShowingNow && this._highlighted_option){dojo.event.browser.stopEvent(evt);this.selectOption({ 'target': this._highlighted_option, 'noHide': false});this.setSelectedRange(this.textInputNode, this.textInputNode.value.length, null);}else{this.selectOption();return;}
break;case k.KEY_ENTER:
if(this.popupWidget.isShowingNow){dojo.event.browser.stopEvent(evt);}
if(this.autoComplete){this.selectOption();return;}
case " ":
if(this.popupWidget.isShowingNow && this._highlighted_option){dojo.event.browser.stopEvent(evt);this.selectOption();this.hideResultList();return;}
break;case k.KEY_ESCAPE:
this.hideResultList();this._prev_key_esc = true;return;case k.KEY_BACKSPACE:
this._prev_key_backspace = true;if(!this.textInputNode.value.length){this.setAllValues("", "");this.hideResultList();doSearch = false;}
break;case k.KEY_RIGHT_ARROW:
case k.KEY_LEFT_ARROW:
doSearch = false;break;default:// non char keys (F1-F12 etc..)  shouldn't open list
if(evt.charCode==0){doSearch = false;}}
if(this.searchTimer){clearTimeout(this.searchTimer);}
if(doSearch){this.blurOptionNode();this.searchTimer = setTimeout(dojo.lang.hitch(this, this.startSearchFromInput), this.searchDelay);}},compositionEnd: function( evt){evt.key = evt.keyCode;this._handleKeyEvents(evt);},onKeyUp: function( evt){this.setValue(this.textInputNode.value);},setSelectedValue: function( value){this.comboBoxSelectionValue.value = value;},setAllValues: function( value1,  value2){this.setSelectedValue(value2);this.setValue(value1);},focusOptionNode: function( node){if(this._highlighted_option != node){this.blurOptionNode();this._highlighted_option = node;dojo.html.addClass(this._highlighted_option, "dojoComboBoxItemHighlight");}},blurOptionNode: function(){if(this._highlighted_option){dojo.html.removeClass(this._highlighted_option, "dojoComboBoxItemHighlight");this._highlighted_option = null;}},highlightNextOption: function(){if((!this._highlighted_option) || !this._highlighted_option.parentNode){this.focusOptionNode(this.optionsListNode.firstChild);}else if(this._highlighted_option.nextSibling){this.focusOptionNode(this._highlighted_option.nextSibling);}
dojo.html.scrollIntoView(this._highlighted_option);},highlightPrevOption: function(){if(this._highlighted_option && this._highlighted_option.previousSibling){this.focusOptionNode(this._highlighted_option.previousSibling);}else{this._highlighted_option = null;this.hideResultList();return;}
dojo.html.scrollIntoView(this._highlighted_option);},itemMouseOver: function( evt){if (evt.target === this.optionsListNode){ return; }
this.focusOptionNode(evt.target);dojo.html.addClass(this._highlighted_option, "dojoComboBoxItemHighlight");},itemMouseOut: function( evt){if (evt.target === this.optionsListNode){ return; }
this.blurOptionNode();},onResize: function(){var inputSize = dojo.html.getContentBox(this.textInputNode);if( inputSize.height == 0 ){dojo.lang.setTimeout(this, "onResize", 50);return;}
var buttonSize = { width: inputSize.height, height: inputSize.height};dojo.html.setContentBox(this.downArrowNode, buttonSize);},fillInTemplate: function( args,  frag){dojo.html.applyBrowserClass(this.domNode);var source = this.getFragNodeRef(frag);if (! this.name && source.name){ this.name = source.name; }
this.comboBoxValue.name = this.name;this.comboBoxSelectionValue.name = this.name+"_selected";dojo.html.copyStyle(this.domNode, source);dojo.html.copyStyle(this.textInputNode, source);dojo.html.copyStyle(this.downArrowNode, source);with (this.downArrowNode.style){width = "0px";height = "0px";}
var dpClass;if(this.mode == "remote"){dpClass = dojo.widget.incrementalComboBoxDataProvider;}else if(typeof this.dataProviderClass == "string"){dpClass = dojo.evalObjPath(this.dataProviderClass)}else{dpClass = this.dataProviderClass;}
this.dataProvider = new dpClass();this.dataProvider.init(this, this.getFragNodeRef(frag));this.popupWidget = new dojo.widget.createWidget("PopupContainer",{toggle: this.dropdownToggle, toggleDuration: this.toggleDuration});dojo.event.connect(this, 'destroy', this.popupWidget, 'destroy');this.optionsListNode = this.popupWidget.domNode;this.domNode.appendChild(this.optionsListNode);dojo.html.addClass(this.optionsListNode, 'dojoComboBoxOptions');dojo.event.connect(this.optionsListNode, 'onclick', this, 'selectOption');dojo.event.connect(this.optionsListNode, 'onmouseover', this, '_onMouseOver');dojo.event.connect(this.optionsListNode, 'onmouseout', this, '_onMouseOut');dojo.event.connect(this.optionsListNode, "onmouseover", this, "itemMouseOver");dojo.event.connect(this.optionsListNode, "onmouseout", this, "itemMouseOut");},focus: function(){this.tryFocus();},openResultList: function( results){if (this.disabled){return;}
this.clearResultList();if(!results.length){this.hideResultList();}
if(	(this.autoComplete)&&
(results.length)&&
(!this._prev_key_backspace)&&
(this.textInputNode.value.length > 0)){var cpos = this.getCaretPos(this.textInputNode);if((cpos+1) > this.textInputNode.value.length){this.textInputNode.value += results[0][0].substr(cpos);this.setSelectedRange(this.textInputNode, cpos, this.textInputNode.value.length);}}
var even = true;while(results.length){var tr = results.shift();if(tr){var td = document.createElement("div");td.appendChild(document.createTextNode(tr[0]));td.setAttribute("resultName", tr[0]);td.setAttribute("resultValue", tr[1]);td.className = "dojoComboBoxItem "+((even) ? "dojoComboBoxItemEven" : "dojoComboBoxItemOdd");even = (!even);this.optionsListNode.appendChild(td);}}
this.showResultList();},onFocusInput: function(){this._hasFocus = true;},onBlurInput: function(){this._hasFocus = false;this._handleBlurTimer(true, 500);},_handleBlurTimer: function(clear,  millisec){if(this.blurTimer && (clear || millisec)){clearTimeout(this.blurTimer);}
if(millisec){this.blurTimer = dojo.lang.setTimeout(this, "checkBlurred", millisec);}},_onMouseOver: function( evt){if(!this._mouseover_list){this._handleBlurTimer(true, 0);this._mouseover_list = true;}},_onMouseOut:function( evt){var relTarget = evt.relatedTarget;if(!relTarget || relTarget.parentNode!=this.optionsListNode){this._mouseover_list = false;this._handleBlurTimer(true, 100);this.tryFocus();}},_isInputEqualToResult: function( result){var input = this.textInputNode.value;if(!this.dataProvider.caseSensitive){input = input.toLowerCase();result = result.toLowerCase();}
return (input == result);},_isValidOption: function(){var tgt = dojo.html.firstElement(this.optionsListNode);var isValidOption = false;while(!isValidOption && tgt){if(this._isInputEqualToResult(tgt.getAttribute("resultName"))){isValidOption = true;}else{tgt = dojo.html.nextElement(tgt);}}
return isValidOption;},checkBlurred: function(){if(!this._hasFocus && !this._mouseover_list){this.hideResultList();if(!this.textInputNode.value.length){this.setAllValues("", "");return;}
var isValidOption = this._isValidOption();if(this.forceValidOption && !isValidOption){this.setAllValues("", "");return;}
if(!isValidOption){this.setSelectedValue("");}}},sizeBackgroundIframe: function(){var mb = dojo.html.getMarginBox(this.optionsListNode);if( mb.width==0 || mb.height==0 ){dojo.lang.setTimeout(this, "sizeBackgroundIframe", 100);return;}},selectOption: function( evt){var tgt = null;if(!evt){evt = { target: this._highlighted_option };}
if(!dojo.html.isDescendantOf(evt.target, this.optionsListNode)){if(!this.textInputNode.value.length){return;}
tgt = dojo.html.firstElement(this.optionsListNode);if(!tgt || !this._isInputEqualToResult(tgt.getAttribute("resultName"))){return;}}else{tgt = evt.target;}
while((tgt.nodeType!=1)||(!tgt.getAttribute("resultName"))){tgt = tgt.parentNode;if(tgt === dojo.body()){return false;}}
this.selectedResult = [tgt.getAttribute("resultName"), tgt.getAttribute("resultValue")];this.setAllValues(tgt.getAttribute("resultName"), tgt.getAttribute("resultValue"));if(!evt.noHide){this.hideResultList();this.setSelectedRange(this.textInputNode, 0, null);}
this.tryFocus();},clearResultList: function(){if(this.optionsListNode.innerHTML){this.optionsListNode.innerHTML = "";}},hideResultList: function(){this.popupWidget.close();},showResultList: function(){var childs = this.optionsListNode.childNodes;if(childs.length){var visibleCount = this.maxListLength;if(childs.length < visibleCount){visibleCount = childs.length;}
with(this.optionsListNode.style)
{display = "";if(visibleCount == childs.length){height = "";}else{height = visibleCount * dojo.html.getMarginBox(childs[0]).height +"px";}
width = (dojo.html.getMarginBox(this.domNode).width-2)+"px";}
this.popupWidget.open(this.domNode, this, this.downArrowNode);}else{this.hideResultList();}},handleArrowClick: function(){this._handleBlurTimer(true, 0);this.tryFocus();if(this.popupWidget.isShowingNow){this.hideResultList();}else{this.startSearch("");}},tryFocus: function(){try {this.textInputNode.focus();} catch (e){};},startSearchFromInput: function(){this.startSearch(this.textInputNode.value);},postCreate: function(){this.onResize();dojo.event.connect(this, "startSearch", this.dataProvider, "startSearch");dojo.event.connect(this.dataProvider, "provideSearchResults", this, "openResultList");dojo.event.connect(this.textInputNode, "onblur", this, "onBlurInput");dojo.event.connect(this.textInputNode, "onfocus", this, "onFocusInput");if (this.disabled){this.disable();}
var s = dojo.widget.html.stabile.getState(this.widgetId);if (s){this.setState(s);}}}
);