
dojo.provide("dojo.widget.Editor2");dojo.require("dojo.io.*");dojo.require("dojo.widget.RichText");dojo.require("dojo.widget.Editor2Toolbar");dojo.require("dojo.i18n.common");dojo.require("dojo.uri.cache");dojo.requireLocalization("dojo.widget", "Editor2", null, "ROOT,de,it");dojo.requireLocalization("dojo.widget", "Editor2BrowserCommand", null, "de,ROOT,it");dojo.widget.Editor2Manager = new dojo.widget.HandlerManager();dojo.lang.mixin(dojo.widget.Editor2Manager,{_currentInstance: null,commandState: {Disabled: 0, Latched: 1, Enabled: 2},getCurrentInstance: function(){return this._currentInstance;},setCurrentInstance: function(inst){this._currentInstance = inst;},getCommand: function(editor,name){var oCommand;name = name.toLowerCase();for(var i=0;i<this._registeredHandlers.length;i++){oCommand = this._registeredHandlers[i](editor, name);if(oCommand){return oCommand;}}
if(name == 'createlink' || name == 'insertimage'){if(!dojo.widget['Editor2Plugin'] || !dojo.widget.Editor2Plugin['DialogCommands']){dojo.deprecated('Command '+name+" is now defined in plugin dojo.widget.Editor2Plugin.DialogCommands. It shall be required explicitly", "0.6");dojo['require']("dojo.widget.Editor2Plugin.DialogCommands");}}
var resources = dojo.i18n.getLocalization("dojo.widget", "Editor2", this.lang);switch(name){case 'htmltoggle':
oCommand = new dojo.widget.Editor2BrowserCommand(editor, name);break;case 'anchor':
oCommand = new dojo.widget.Editor2Command(editor, name);break;case 'createlink':
oCommand = new dojo.widget.Editor2DialogCommand(editor, name,{contentFile: "dojo.widget.Editor2Plugin.CreateLinkDialog",contentClass: "Editor2CreateLinkDialog",title: resources.createLinkDialogTitle, width: "300px", height: "200px",lang: this.lang});break;case 'insertimage':
oCommand = new dojo.widget.Editor2DialogCommand(editor, name,{contentFile: "dojo.widget.Editor2Plugin.InsertImageDialog",contentClass: "Editor2InsertImageDialog",title: resources.insertImageDialogTitle, width: "400px", height: "270px",lang: this.lang});break;default:
var curtInst = this.getCurrentInstance();if((curtInst && curtInst.queryCommandAvailable(name)) ||
(!curtInst && dojo.widget.Editor2.prototype.queryCommandAvailable(name))){oCommand = new dojo.widget.Editor2BrowserCommand(editor, name);}else{dojo.debug("dojo.widget.Editor2Manager.getCommand: Unknown command "+name);return;}}
return oCommand;},destroy: function(){this._currentInstance = null;dojo.widget.HandlerManager.prototype.destroy.call(this);}});dojo.addOnUnload(dojo.widget.Editor2Manager, "destroy");dojo.lang.declare("dojo.widget.Editor2Command",null,function(editor,name){this._editor = editor;this._updateTime = 0;this._name = name;},{_text: 'Unknown',execute: function(para){dojo.unimplemented("dojo.widget.Editor2Command.execute");},getText: function(){return this._text;},getState: function(){return dojo.widget.Editor2Manager.commandState.Enabled;},destroy: function(){}}
);dojo.lang.declare("dojo.widget.Editor2BrowserCommand", dojo.widget.Editor2Command,function(editor,name){var browserCommandNames = dojo.i18n.getLocalization("dojo.widget", "Editor2BrowserCommand", editor.lang);var text = browserCommandNames[name.toLowerCase()];if(text){this._text = text;}},{execute: function(para){this._editor.execCommand(this._name, para);},getState: function(){if(this._editor._lastStateTimestamp > this._updateTime || this._state == undefined){this._updateTime = this._editor._lastStateTimestamp;try{if(this._editor.queryCommandEnabled(this._name)){if(this._editor.queryCommandState(this._name)){this._state = dojo.widget.Editor2Manager.commandState.Latched;}else{this._state = dojo.widget.Editor2Manager.commandState.Enabled;}}else{this._state = dojo.widget.Editor2Manager.commandState.Disabled;}}catch (e) {this._state = dojo.widget.Editor2Manager.commandState.Enabled;}}
return this._state;},getValue: function(){try{return this._editor.queryCommandValue(this._name);}catch(e){}}
}
);dojo.widget.Editor2ToolbarGroups = {};dojo.widget.defineWidget(
"dojo.widget.Editor2",dojo.widget.RichText,function(){this._loadedCommands={};},{toolbarAlwaysVisible: false,toolbarWidget: null,scrollInterval: null,toolbarTemplatePath: dojo.uri.cache.allow(dojo.uri.moduleUri("dojo.widget", "templates/EditorToolbarOneline.html")),toolbarTemplateCssPath: dojo.uri.cache.allow(dojo.uri.moduleUri("dojo.widget", "templates/EditorToolbar.css")),toolbarPlaceHolder: '',_inSourceMode: false,_htmlEditNode: null,toolbarGroup: '',shareToolbar: false,contextMenuGroupSet: '',editorOnLoad: function(){dojo.event.topic.publish("dojo.widget.Editor2::preLoadingToolbar", this);if(this.toolbarAlwaysVisible){dojo.require("dojo.widget.Editor2Plugin.AlwaysShowToolbar");}
if(this.toolbarWidget){this.toolbarWidget.show();dojo.html.insertBefore(this.toolbarWidget.domNode, this.domNode.firstChild);}else{if(this.shareToolbar){dojo.deprecated("Editor2:shareToolbar is deprecated in favor of toolbarGroup", "0.5");this.toolbarGroup = 'defaultDojoToolbarGroup';}
if(this.toolbarGroup){if(dojo.widget.Editor2ToolbarGroups[this.toolbarGroup]){this.toolbarWidget = dojo.widget.Editor2ToolbarGroups[this.toolbarGroup];}}
if(!this.toolbarWidget){var tbOpts = {shareGroup: this.toolbarGroup, parent: this, lang: this.lang};tbOpts.templateString = dojo.uri.cache.get(this.toolbarTemplatePath);if(this.toolbarTemplateCssPath){tbOpts.templateCssPath = this.toolbarTemplateCssPath;tbOpts.templateCssString = dojo.uri.cache.get(this.toolbarTemplateCssPath);}
if(this.toolbarPlaceHolder){this.toolbarWidget = dojo.widget.createWidget("Editor2Toolbar", tbOpts, dojo.byId(this.toolbarPlaceHolder), "after");}else{this.toolbarWidget = dojo.widget.createWidget("Editor2Toolbar", tbOpts, this.domNode.firstChild, "before");}
if(this.toolbarGroup){dojo.widget.Editor2ToolbarGroups[this.toolbarGroup] = this.toolbarWidget;}
dojo.event.connect(this, "close", this.toolbarWidget, "hide");this.toolbarLoaded();}}
dojo.event.topic.registerPublisher("Editor2.clobberFocus", this, "clobberFocus");dojo.event.topic.subscribe("Editor2.clobberFocus", this, "setBlur");dojo.event.topic.publish("dojo.widget.Editor2::onLoad", this);},toolbarLoaded: function(){},registerLoadedPlugin: function(obj){if(!this.loadedPlugins){this.loadedPlugins = [];}
this.loadedPlugins.push(obj);},unregisterLoadedPlugin: function(obj){for(var i in this.loadedPlugins){if(this.loadedPlugins[i] === obj){delete this.loadedPlugins[i];return;}}
dojo.debug("dojo.widget.Editor2.unregisterLoadedPlugin: unknown plugin object: "+obj);},execCommand: function(command, argument){switch(command.toLowerCase()){case 'htmltoggle':
this.toggleHtmlEditing();break;default:
dojo.widget.Editor2.superclass.execCommand.apply(this, arguments);}},queryCommandEnabled: function(command, argument){switch(command.toLowerCase()){case 'htmltoggle':
return true;default:
if(this._inSourceMode){ return false;}
return dojo.widget.Editor2.superclass.queryCommandEnabled.apply(this, arguments);}},queryCommandState: function(command, argument){switch(command.toLowerCase()){case 'htmltoggle':
return this._inSourceMode;default:
return dojo.widget.Editor2.superclass.queryCommandState.apply(this, arguments);}},onClick: function(e){dojo.widget.Editor2.superclass.onClick.call(this, e);if(dojo.widget.PopupManager){if(!e){e = this.window.event;}
dojo.widget.PopupManager.onClick(e);}},clobberFocus: function(){},toggleHtmlEditing: function(){if(this===dojo.widget.Editor2Manager.getCurrentInstance()){if(!this._inSourceMode){var html = this.getEditorContent();this._inSourceMode = true;if(!this._htmlEditNode){this._htmlEditNode = dojo.doc().createElement("textarea");dojo.html.insertAfter(this._htmlEditNode, this.editorObject);}
this._htmlEditNode.style.display = "";this._htmlEditNode.style.width = "100%";this._htmlEditNode.style.height = dojo.html.getBorderBox(this.editNode).height+"px";this._htmlEditNode.value = html;with(this.editorObject.style){position = "absolute";left = "-2000px";top = "-2000px";}}else{this._inSourceMode = false;this._htmlEditNode.blur();with(this.editorObject.style){position = "";left = "";top = "";}
var html = this._htmlEditNode.value;dojo.lang.setTimeout(this, "replaceEditorContent", 1, html);this._htmlEditNode.style.display = "none";this.focus();}
this.onDisplayChanged(null, true);}},setFocus: function(){if(dojo.widget.Editor2Manager.getCurrentInstance() === this){ return; }
this.clobberFocus();dojo.widget.Editor2Manager.setCurrentInstance(this);},setBlur: function(){},saveSelection: function(){this._bookmark = null;this._bookmark = dojo.withGlobal(this.window, dojo.html.selection.getBookmark);},restoreSelection: function(keepbookmark){if(this._bookmark){this.focus();dojo.withGlobal(this.window, "moveToBookmark", dojo.html.selection, [this._bookmark]);if(keepbookmark){this._bookmark = null;}}else{dojo.debug("restoreSelection: no saved selection is found!");}},_updateToolbarLastRan: null,_updateToolbarTimer: null,_updateToolbarFrequency: 500,updateToolbar: function(force){if((!this.isLoaded)||(!this.toolbarWidget)){ return; }
var diff = new Date() - this._updateToolbarLastRan;if( (!force)&&(this._updateToolbarLastRan)&&
((diff < this._updateToolbarFrequency)) ){clearTimeout(this._updateToolbarTimer);var _this = this;this._updateToolbarTimer = setTimeout(function() {_this.updateToolbar();}, this._updateToolbarFrequency/2);return;}else{this._updateToolbarLastRan = new Date();}
if(dojo.widget.Editor2Manager.getCurrentInstance() !== this){ return; }
this.toolbarWidget.update();},destroy: function(finalize){this._htmlEditNode = null;dojo.event.disconnect(this, "close", this.toolbarWidget, "hide");if(!finalize){this.toolbarWidget.destroy();}
dojo.widget.Editor2.superclass.destroy.call(this);},_lastStateTimestamp: 0,onDisplayChanged: function(e, forceUpdate){this._lastStateTimestamp = (new Date()).getTime();dojo.widget.Editor2.superclass.onDisplayChanged.call(this,e);this.updateToolbar(forceUpdate);},onLoad: function(){try{dojo.widget.Editor2.superclass.onLoad.call(this);}catch(e){dojo.debug(e);}
this.editorOnLoad();},onFocus: function(){dojo.widget.Editor2.superclass.onFocus.call(this);this.setFocus();},getEditorContent: function(){if(this._inSourceMode){return this._htmlEditNode.value;}
return dojo.widget.Editor2.superclass.getEditorContent.call(this);},replaceEditorContent: function(html){if(this._inSourceMode){this._htmlEditNode.value = html;return;}
dojo.widget.Editor2.superclass.replaceEditorContent.apply(this,arguments);},getCommand: function(name){if(this._loadedCommands[name]){return this._loadedCommands[name];}
var cmd = dojo.widget.Editor2Manager.getCommand(this, name);this._loadedCommands[name] = cmd;return cmd;},shortcuts: [['bold'],['italic'],['underline'],['selectall','a'],['insertunorderedlist','\\']],setupDefaultShortcuts: function(){var exec = function(cmd){ return function(){ cmd.execute(); }};var self = this;dojo.lang.forEach(this.shortcuts, function(item){var cmd = self.getCommand(item[0]);if(cmd){self.addKeyHandler(item[1]?item[1]:item[0].charAt(0), item[2]==undefined?self.KEY_CTRL:item[2], exec(cmd));}});}}
);