<?xml version="1.0"?>
<!DOCTYPE script PUBLIC
	"-//Apache Software Foundation//Tapestry Script Specification 3.0//EN"
	"http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">

<script>

<body>
<unique tag="tag1">Block1</unique>
<unique tag="tag1">Block2</unique>
<unique tag="tag1">Block3</unique>
<unique tag="tag2">Block4</unique>
<unique tag="tag2">Block5</unique>
	
</body>


</script>