# $Id$

MAIN_DOCUMENT =	DevelopersGuide.xml

HTML_STYLESHEET := ../common/Tapestry.xsl

HTML_INSTALL_DIR := ../../DevelopersGuide

DOCUMENT_RESOURCES = images

USE_STANDARD_IMAGES := t

include $(SYS_MAKEFILE_DIR)/DocBook.mk
