# $Id$

MAIN_DOCUMENT =	DevelopersGuide.xml

OTHER_DOC_FILES := *.xml

HTML_INSTALL_DIR := ../../DevelopersGuide

DOCUMENT_RESOURCES = images

USE_STANDARD_IMAGES := t

HTML_XSLT_OPTS := -TT

include $(SYS_MAKEFILE_DIR)/DocBook.mk
