<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE script PUBLIC
  "-//Apache Software Foundation//Tapestry Script Specification 3.0//EN" 
  "http://jakarta.apache.org/tapestry/dtd/Script_3_0.dtd">

<script>
    <input-symbol key="id" required="yes" />
    <body>
        <unique>
            dojo.require("tapestry.fx");
        </unique>
    </body>
    <initialization>
if(tapestry.fx) tapestry.fx.attachAjaxStatus("${id}");
    </initialization>
</script>