<?xml version="1.0"?>
<!-- $Id$ -->

<!DOCTYPE script PUBLIC 
	"-//Howard Lewis Ship//Tapestry Script 1.2//EN"
	"http://tapestry.sf.net/dtd/Script_1_2.dtd">
	
<!-- 

  Creates a script for validating that a field is required and/or has a minimum
  field length.
  
  Input symbols:
     field, form, validator:  As normal for a validation script.
     formatMessage: Message displayed if the input is not valid.
	 requiredMessage: Message to display if the field is required yet blank.
	 rangeMessage: Message to display if the field is not in the expected range. 
     formatExpression: Regular expression for the field.
-->
	
<script>

<input-symbol key="field" class="net.sf.tapestry.valid.ValidField" required="yes"/>
<input-symbol key="form" class="net.sf.tapestry.IForm" required="yes"/>
<input-symbol key="validator" class="net.sf.tapestry.valid.NumberValidator" required="yes"/>
<input-symbol key="formatMessage" class="java.lang.String" required="yes"/>
<input-symbol key="formatExpression" class="java.lang.String" required="yes"/>
<input-symbol key="requiredMessage" class="java.lang.String"/>
<input-symbol key="rangeMessage" class="java.lang.String"/>

<let key="function">
validate_${form.name}_${field.name}
</let>

<body>
function ${function}()
{
  var field = document.${form.name}.${field.name};
 
<!--
  
  var matches = field.value.match(/${formatExpression}/);
    
  if (matches == null)
  {
    field.focus();
    field.select();
    window.alert("${formatMessage}");
    return false;
  }
  
  var value = matches[0];
  
  window.alert("value=" + value);
  
-->

  var value = field.value;
  
<if expression="validator.required">
  if (value.length == 0)
  {
  	 field.focus();
  	 field.select();
     window.alert("${requiredMessage}");
     return false;
  }
</if>
<if expression="validator.minimum != null">
  if (value &lt; ${validator.minimum})
  {
  	field.focus();
  	field.select();
	window.alert("${rangeMessage}");
    return false;
  }
</if>

<if expression="validator.maximum != null">
  if (value &gt; ${validator.maximum})
  {
  	field.focus();
  	field.select();
	window.alert("${rangeMessage}");
    return false;
  }
</if>

  return true;
}
</body>

</script>