<?xml version="1.0"?>
<!-- 
   Copyright 2005 The Apache Software Foundation

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->

<!DOCTYPE script PUBLIC 
	"-//Howard Lewis Ship//Tapestry Script 1.2//EN"
	"http://tapestry.sf.net/dtd/Script_1_2.dtd">
	
<script>

<let key="functionName">
	${component.form.name}_${component.name}
</let>

<!-- Test a few variations.  -->

<let key="incomplete1">
Incomplete: $</let>

<let key="incomplete2">
Incomplete: ${</let>

<let key="nopath">
This ${} ends up as literal.
</let>

<let key="OGNL">
This is a brace: ${"{Hello}".toCharArray()[6]}.
</let>

</script>
