# $Id$

MAIN_DOCUMENT =	JBE.sgml

HTML_INSTALL_DIR := ../../JBE

DOCUMENT_RESOURCES = images

HTML_VARIABLE_DEFS := %shade-verbatim% %use-id-as-filename%

USE_STANDARD_IMAGES := t

include $(SYS_MAKEFILE_DIR)/DocBook.mk
