# $Id$

MAIN_DOCUMENT =	JBE.sgml

HTML_INSTALL_DIR := ../../doc/JBE

RTF_INSTALL_DIR := ../../doc/rtf/JBE

DOCUMENT_RESOURCES = images

HTML_VARIABLE_DEFS := %shade-verbatim%

FORMATS := rtf html

include $(SYS_MAKEFILE_DIR)/DocBook.mk
