# $Id$

MAIN_DOCUMENT =	Tutorial.sgml

OTHER_DOC_FILES := *.sgml

HTML_VARIABLE_DEFS := %shade-verbatim% %use-id-as-filename%

HTML_INSTALL_DIR := ../../doc/Tutorial

DOCUMENT_RESOURCES = images

include $(SYS_MAKEFILE_DIR)/DocBook.mk
