# $Id$

MODULE_NAME = Vlib

PACKAGES = \
	com.primix.vlib \
	com.primix.vlib.pages \
	com.primix.vlib.components

LOCAL_CLASSPATH = \
	$(INSTALL_DIR)/j2ee.jar \
	$(INSTALL_DIR)/xerces.jar \
	$(INSTALL_DIR)/PrimixFoundation.jar \
	$(INSTALL_DIR)/Tapestry.jar \
	$(INSTALL_DIR)/VlibBeans.jar

INSTALL_DIR = ../../lib

JAVADOC_DIR = ../../javadoc

WEB_INF_RESOURCES = weblogic.xml

include $(SYS_MAKEFILE_DIR)/War.mk
