# $Id$

JAVA_FILES = *.java

PACKAGES = com.primix.sesstrack

MODULE_NAME = SessionTracker

LOCAL_CLASSPATH = ../../lib/log.jar

EJBC_OPT = -keepgenerated

INSTALL_DIR = ../../lib

include $(SYS_MAKEFILE_DIR)/WebLogic.mk





